global:
  scrape_interval: 5s
scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'dp-testserver'
    metrics_path: /metrics
    static_configs:
      - targets: ['netsim:9920']
#  - job_name: 'jvm'
#    metrics_path: /metrics
#    static_configs:
#      - targets: ['netsim:9921']
